export interface SellerTrade { id: number; symbol: string; sellQty: number; buyQty: number; avgSellPrice: number; avgBuyPrice: number; netPnl: number; riskAmount: number | null; entryIv: number | null; exitIv: number | null; entryDte: number | null; hedgeStatus: string | null; expiryOutcome: string | null; adjustmentGroup: string | null; isOpen: boolean; }
export interface SellerRow { id: number; symbol: string; premiumSold: number; premiumCaptured: number; capturePct: number | null; ivChange: number | null; returnOnRiskPct: number | null; }
export function optionsSellerReport(trades: SellerTrade[]) {
  const sellers = trades.filter((t) => t.sellQty > 0 && (t.sellQty >= t.buyQty || t.avgSellPrice > 0));
  const rows: SellerRow[] = sellers.map((t) => { const qty = t.sellQty; const sold = t.avgSellPrice * qty; const bought = t.avgBuyPrice * Math.min(t.buyQty, qty); const captured = sold - bought; return { id: t.id, symbol: t.symbol, premiumSold: Math.round(sold*100)/100, premiumCaptured: Math.round(captured*100)/100, capturePct: sold > 0 ? Math.round(captured/sold*10000)/100 : null, ivChange: t.entryIv != null && t.exitIv != null ? Math.round((t.exitIv-t.entryIv)*100)/100 : null, returnOnRiskPct: t.riskAmount && t.riskAmount > 0 ? Math.round(t.netPnl/t.riskAmount*10000)/100 : null }; });
  const closed = sellers.filter((t) => !t.isOpen); const premiumSold = rows.reduce((s,r) => s+r.premiumSold,0); const captured = rows.reduce((s,r) => s+r.premiumCaptured,0);
  const outcomes = Object.fromEntries([...new Set(sellers.map((t) => t.expiryOutcome ?? "unclassified"))].map((k) => [k, sellers.filter((t) => (t.expiryOutcome ?? "unclassified") === k).length]));
  return { rows, count: sellers.length, closed: closed.length, netPnl: sellers.reduce((s,t)=>s+t.netPnl,0), capturePct: premiumSold > 0 ? Math.round(captured/premiumSold*10000)/100 : null, hedgedPct: sellers.length ? Math.round(sellers.filter((t)=>t.hedgeStatus === "hedged").length/sellers.length*10000)/100 : null, completeIv: sellers.filter((t)=>t.entryIv != null && t.exitIv != null).length, outcomes };
}
