"use client";
import { useMemo, useState } from "react";
import { CartesianGrid, ComposedChart, Legend, Line, ReferenceLine, ResponsiveContainer, Scatter, Tooltip, XAxis, YAxis } from "recharts";
import { Select } from "@/components/ui/select";

export interface ReplayTrade { id: number; symbol: string; entry: number; exit: number | null; stop: number | null; target: number | null; bars: { date: string; close: number }[]; legs: { id: number; kind: string; tradeDate: string; price: number; qty: number }[]; }
export function TradeReplay({ trades }: { trades: ReplayTrade[] }) {
  const [id, setId] = useState(trades[0]?.id ?? 0); const trade = trades.find((t) => t.id === id) ?? trades[0];
  const data = useMemo(() => trade?.bars.map((b) => ({ ...b, entry: trade.legs.some((l) => l.kind === "entry" && l.tradeDate === b.date) ? trade.legs.find((l) => l.kind === "entry" && l.tradeDate === b.date)!.price : null, exit: trade.legs.some((l) => l.kind === "exit" && l.tradeDate === b.date) ? trade.legs.find((l) => l.kind === "exit" && l.tradeDate === b.date)!.price : null })) ?? [], [trade]);
  if (!trade) return <p className="text-sm text-muted-foreground">No staged position has EOD price-history coverage yet.</p>;
  return <div className="space-y-4"><Select value={String(trade.id)} onChange={(e) => setId(Number(e.target.value))}>{trades.map((t) => <option key={t.id} value={t.id}>#{t.id} · {t.symbol}</option>)}</Select>
    <div className="h-80"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{ top: 10, right: 14, left: 4, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" opacity={0.2}/><XAxis dataKey="date" tick={{ fontSize: 10 }}/><YAxis domain={["auto","auto"]} tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ background: "var(--color-card)", borderColor: "var(--color-border)", fontSize: 12 }}/><Legend/><Line type="monotone" dataKey="close" stroke="var(--color-primary)" dot={false} strokeWidth={2}/><Scatter dataKey="entry" name="Entry/add" fill="var(--color-profit)"/><Scatter dataKey="exit" name="Exit" fill="var(--color-loss)"/>{trade.stop != null && <ReferenceLine y={trade.stop} stroke="var(--color-loss)" strokeDasharray="5 4" label="SL"/>}{trade.target != null && <ReferenceLine y={trade.target} stroke="var(--color-profit)" strokeDasharray="5 4" label="Target"/>}</ComposedChart></ResponsiveContainer></div>
    <div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-y border-border text-left text-muted-foreground"><th className="p-2">Seq</th><th className="p-2">Date</th><th className="p-2">Action</th><th className="p-2 text-right">Qty</th><th className="p-2 text-right">Price</th></tr></thead><tbody>{trade.legs.map((l,i) => <tr key={l.id} className="border-b border-rule"><td className="p-2">{i+1}</td><td className="p-2">{l.tradeDate}</td><td className={l.kind === "entry" ? "p-2 text-profit" : "p-2 text-loss"}>{l.kind}</td><td className="p-2 text-right">{l.qty}</td><td className="p-2 text-right">{l.price}</td></tr>)}</tbody></table></div>
    <p className="text-[11px] text-muted-foreground">EOD closes cannot show the intraday path between fills. Markers use recorded fill prices; the line uses imported bhavcopy closes.</p></div>;
}
