import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { PRICING, formatInr, offerPct } from "@/lib/domain/pricing";
import { COMPETITORS } from "@/lib/domain/pricing-comparison";

/**
 * PRICE SURFACES GUARD — v3.9.1.
 *
 * The 2026-08-31 reprice (annual ₹9,999 → ₹7,999, anchor unchanged, so the
 * derived badge moved 23% → 38%) changed lib/domain/pricing.ts and the landing
 * page's price CARD. It did not change six prose surfaces: the landing page's
 * own comparison table (two rows), the brochure's offer tag, the client README
 * twice, this repo's README four times, and the Vyuha row of
 * lib/domain/pricing-comparison.ts. `tests/pricing.test.ts` pins the app's
 * amounts to the landing page's price cells, so it stayed green while a buyer
 * could read two different annual prices on ONE page. Nothing scanned prose.
 *
 * This does. Every allowed figure is DERIVED from PRICING — the price, the
 * anchor and offerPct() — so a future reprice makes this test fail until the
 * prose follows, and no price is ever hand-typed here (docs/DECISIONS.md
 * 2026-09-06).
 *
 * What it deliberately does NOT flag: competitor prices (derived from
 * COMPETITORS), approximate conversions (`≈ ₹27,700/yr`), ranges
 * (`₹47,000–95,000`), and amounts with no price context near them (a ₹1,500 cr
 * exposure limit is not an offer). History files (CHANGELOG.md,
 * docs/DECISIONS.md, docs/prompts/**, docs/owner/**) are not scanned — they
 * record what was once true and are never rewritten.
 */

const ROOT = path.resolve(__dirname, "..");

/** Buyer-facing surfaces that quote, or could quote, what Vyuha costs. */
const SURFACES = [
  "README.md",
  "docs/sales/landing-page.html",
  "docs/sales/brochure.html",
  "docs/client/README.md",
  "docs/client/GETTING_STARTED_DECK.html",
  "lib/domain/pricing-comparison.ts",
] as const;

/** Generated by scripts/build-landing.mjs, .gitignore(d) — scanned when present. */
const GENERATED = "docs/sales/landing-page.standalone.html";

const read = (rel: string) => fs.readFileSync(path.join(ROOT, rel), "utf8");

/** Every rupee figure PRICING itself authorises: the prices and their anchors. */
const ALLOWED_AMOUNTS = new Set(
  PRICING.flatMap((s) => [formatInr(s.amountInr), ...(s.wasInr != null ? [formatInr(s.wasInr)] : [])]),
);

/** Every savings percentage PRICING itself derives. Never hand-typed. */
const ALLOWED_PCT = new Set(PRICING.map((s) => offerPct(s)).filter((p): p is number => p != null));

/** Digit groups that belong to a competitor, read out of COMPETITORS' own cells. */
const COMPETITOR_FIGURES = new Set(
  COMPETITORS.flatMap((c) => [...`${c.cheapestPaid} ${c.model}`.matchAll(/\d{1,2},\d{3}/g)].map((m) => m[0])),
);

/** ₹9,999-shaped figures. Decimals (₹8,268.27) are amounts of P&L, not prices. */
const AMOUNT_RE = /₹\s?(\d{1,2},\d{3})(?![\d,]|\.\d)/g;

/** Words that make a nearby rupee figure a PRICE rather than any other number. */
const PRICE_CONTEXT = /\/yr|per year|annual|lifetime|once|(?<![a-z])ever(?![a-z])/i;

const WINDOW = 60;

/** A figure inside `₹47,000–95,000` or `≈ ₹27,700` is never one of our two prices. */
function isRangeOrApprox(text: string, start: number, end: number): boolean {
  const before = text.slice(Math.max(0, start - 3), start);
  const after = text.slice(end, end + 2);
  return /[–—-]\s?$/.test(before) || /≈\s?$/.test(before) || /^[–—-]\d/.test(after);
}

interface Hit {
  where: string;
  amount: string;
  line: number;
  excerpt: string;
}

function strayPrices(rel: string, text: string): Hit[] {
  const out: Hit[] = [];
  for (const m of text.matchAll(AMOUNT_RE)) {
    const start = m.index ?? 0;
    const end = start + m[0].length;
    const amount = `₹${m[1]}`;
    if (ALLOWED_AMOUNTS.has(amount)) continue;
    if (COMPETITOR_FIGURES.has(m[1])) continue;
    if (isRangeOrApprox(text, start, end)) continue;
    const context = text.slice(Math.max(0, start - WINDOW), end + WINDOW);
    if (!PRICE_CONTEXT.test(context)) continue;
    out.push({
      where: rel,
      amount,
      line: text.slice(0, start).split("\n").length,
      excerpt: context.replace(/\s+/g, " ").trim(),
    });
  }
  return out;
}

describe("price surfaces carry no price PRICING does not authorise", () => {
  it.each([...SURFACES, GENERATED])("%s quotes only derived rupee figures", (rel) => {
    if (!fs.existsSync(path.join(ROOT, rel))) return; // generated artefact, absent in a fresh clone
    const hits = strayPrices(rel, read(rel));
    expect(
      hits,
      `stale price string in ${rel}:\n${hits.map((h) => `  :${h.line}  ${h.amount}  …${h.excerpt}…`).join("\n")}`,
    ).toEqual([]);
  });

  it.each([...SURFACES, GENERATED])("%s quotes only offerPct()-derived savings badges", (rel) => {
    if (!fs.existsSync(path.join(ROOT, rel))) return;
    const text = read(rel);
    const bad: string[] = [];
    for (const m of text.matchAll(/(\d{1,2})\s?%\s?off/gi)) {
      if (ALLOWED_PCT.has(Number(m[1]))) continue;
      const line = text.slice(0, m.index ?? 0).split("\n").length;
      bad.push(`${rel}:${line}  ${m[0]}  (derived: ${[...ALLOWED_PCT].join("%, ")}%)`);
    }
    expect(bad, `savings badge that offerPct() does not derive:\n${bad.join("\n")}`).toEqual([]);
  });

  it("the guard cannot be satisfied by deleting the price — every selling surface still quotes it", () => {
    // A "no other price" test passes trivially on a page with no price at all,
    // which is the exact funnel leak lib/domain/pricing.ts exists to fix.
    const annual = formatInr(PRICING.find((s) => s.term === "annual")!.amountInr);
    const lifetime = formatInr(PRICING.find((s) => s.term === "lifetime")!.amountInr);
    for (const rel of ["README.md", "docs/sales/landing-page.html", "docs/sales/brochure.html", "docs/client/README.md"]) {
      const text = read(rel);
      expect(text, `${rel} no longer quotes the annual price`).toContain(annual);
      expect(text, `${rel} no longer quotes the lifetime price`).toContain(lifetime);
    }
  });

  it("the derived figures are the ones the owner ruled on 2026-08-31", () => {
    // Belt and braces: if PRICING itself is edited to something the owner did
    // not rule, the scans above would happily bless the new number everywhere.
    expect([...ALLOWED_AMOUNTS].sort()).toEqual(["₹13,000", "₹29,999", "₹35,999", "₹7,999"].sort());
    expect([...ALLOWED_PCT].sort((a, b) => a - b)).toEqual([16, 38]);
  });
});
