/**
 * Assembler — turns the recorded takes into the tour video, no editor needed.
 *
 *   node scripts/demo-video/assemble.mjs                     → silent master + cue sheet
 *   node scripts/demo-video/assemble.mjs --voice=voice-dir   → adds T-0.mp3 … T-12.mp3 at the cues
 *   node scripts/demo-video/assemble.mjs --voice=dir --music=track.mp3   → + looped music bed at −20 dB, faded out at the end
 *
 * Inputs:  demo-takes/01-*.webm … 11-*.webm  (from record.mjs)
 *          docs/owner/demo-video/04-end-card.html (screenshotted automatically)
 * Output:  demo-takes/master-silent.mp4  (or master-voiced.mp4)
 *          demo-takes/CUE-SHEET.md — exact timecode for every narration block
 *
 * The four lower-thirds from the tour EDIT-SHEET are burned in with drawtext,
 * so the only remaining human step is voice (and optionally music) — and with
 * --voice, not even that.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const TAKES = path.join(root, "demo-takes");
const args = Object.fromEntries(process.argv.slice(2).filter((a) => a.startsWith("--")).map((a) => {
  const [k, v] = a.replace(/^--/, "").split("=");
  return [k, v ?? true];
}));

const ff = (fargs, opts = {}) => execFileSync("ffmpeg", ["-y", "-hide_banner", "-loglevel", "error", ...fargs], { stdio: ["ignore", "inherit", "inherit"], ...opts });
const probe = (file) =>
  Number(execFileSync("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "default=nw=1:nk=1", file], { encoding: "utf8" }).trim());

const ENDCARD_SECONDS = 7;
/** Lower-thirds: [sceneIndex (1-based), text, secondsIntoScene, holdSeconds] */
const LOWER_THIRDS = [
  [1, "Runs entirely on your computer — no cloud, no telemetry", 4, 5],
  [3, "One book per account · aggregate view is read-only", 4, 5],
  [8, "Charges recomputed from your rate card, before anything is saved", 6, 5],
  [9, "Verified against brokers' signed contract notes", 4, 5],
];
/** Voice cues: [clip, sceneIndex it starts with, secondsIntoScene] */
const VOICE_CUES = [
  ["T-0", 1, 0.5], ["T-1", 1, 20], ["T-2", 2, 1], ["T-3", 3, 1], ["T-4", 4, 1],
  ["T-5", 5, 1], ["T-6", 6, 1], ["T-7", 7, 1], ["T-8", 8, 1], ["T-9", 9, 1],
  ["T-10", 10, 1], ["T-11", 11, 1], ["T-12", 12, 0.5], // 12 = the end card
];

const tc = (s) => `${String(Math.floor(s / 60)).padStart(2, "0")}:${String(Math.floor(s % 60)).padStart(2, "0")}`;

async function endCardPng() {
  const png = path.join(TAKES, "end-card.png");
  const { chromium } = await import("@playwright/test");
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
  await page.goto("file://" + path.join(root, "docs", "owner", "demo-video", "04-end-card.html").replace(/\\/g, "/"));
  await page.waitForTimeout(800);
  await page.screenshot({ path: png });
  await browser.close();
  return png;
}

async function main() {
  const takes = fs.readdirSync(TAKES).filter((f) => /^\d{2}-.*\.webm$/.test(f) && !f.includes("FAILED")).sort();
  if (takes.length !== 11) {
    console.error(`✗ expected 11 takes in ${TAKES}, found ${takes.length} — run record.mjs first`);
    process.exit(1);
  }

  // Scene timeline.
  const durations = takes.map((f) => probe(path.join(TAKES, f)));
  const starts = [];
  let acc = 0;
  for (const d of durations) { starts.push(acc); acc += d; }
  const endCardStart = acc;
  const total = acc + ENDCARD_SECONDS;

  // Cue sheet FIRST — it is useful even if assembly is interrupted.
  const cueLines = [
    "# Cue sheet — generated by assemble.mjs",
    "",
    `Total runtime: ${tc(total)} (${takes.length} scenes + ${ENDCARD_SECONDS}s end card)`,
    "",
    "| Scene | Starts | Duration | Voice clip | Voice starts at |",
    "|---|---|---|---|---|",
  ];
  for (let i = 0; i < takes.length; i++) {
    const cues = VOICE_CUES.filter(([, s]) => s === i + 1)
      .map(([clip, , off]) => `${clip} @ ${tc(starts[i] + off)}`).join(", ");
    cueLines.push(`| ${takes[i]} | ${tc(starts[i])} | ${Math.round(durations[i])}s | ${cues || "—"} | see left |`);
  }
  cueLines.push(`| end card | ${tc(endCardStart)} | ${ENDCARD_SECONDS}s | T-12 @ ${tc(endCardStart + 0.5)} | |`);
  cueLines.push("", "Lower-thirds are already burned into the master. If placing voice by hand in",
    "Clipchamp: drop each T-clip so it STARTS at its timecode above. Music at −20 dB.");
  fs.writeFileSync(path.join(TAKES, "CUE-SHEET.md"), cueLines.join("\n"));
  console.log("→ cue sheet written");

  // End card still → short video segment.
  console.log("→ rendering end card …");
  const png = await endCardPng();

  // Build the drawtext filters with GLOBAL time windows.
  const fontfile = "C\\:/Windows/Fonts/segoeui.ttf";
  const drawtexts = LOWER_THIRDS.map(([scene, text, off, hold]) => {
    const t0 = (starts[scene - 1] + off).toFixed(2);
    const t1 = (starts[scene - 1] + off + hold).toFixed(2);
    // ffmpeg filter args are single-quoted: a literal apostrophe cannot be
    // backslash-escaped there. The typographic ’ renders identically and
    // needs no escaping at all.
    const safe = text.replace(/'/g, "\u2019").replace(/:/g, "\\:").replace(/%/g, "%%");
    return `drawtext=fontfile='${fontfile}':text='${safe}':fontsize=34:fontcolor=white:` +
      `box=1:boxcolor=black@0.55:boxborderw=18:x=64:y=h-140:enable='between(t,${t0},${t1})'`;
  }).join(",");

  // Concat list for the takes.
  const listFile = path.join(TAKES, "concat.txt");
  fs.writeFileSync(listFile, takes.map((f) => `file '${path.join(TAKES, f).replace(/\\/g, "/").replace(/'/g, "'\\''")}'`).join("\n"));

  console.log("→ encoding scenes (h264, lower-thirds burned) …");
  const scenesMp4 = path.join(TAKES, "_scenes.mp4");
  ff(["-f", "concat", "-safe", "0", "-i", listFile,
    "-vf", `${drawtexts},fps=30,format=yuv420p`,
    "-c:v", "libx264", "-preset", "medium", "-crf", "19", "-an", scenesMp4]);

  console.log("→ encoding end card …");
  const cardMp4 = path.join(TAKES, "_card.mp4");
  ff(["-loop", "1", "-t", String(ENDCARD_SECONDS), "-i", png,
    "-vf", "fps=30,format=yuv420p,fade=t=in:st=0:d=0.6",
    "-c:v", "libx264", "-preset", "medium", "-crf", "19", "-an", cardMp4]);

  console.log("→ joining …");
  const joinList = path.join(TAKES, "concat2.txt");
  fs.writeFileSync(joinList, [scenesMp4, cardMp4].map((f) => `file '${f.replace(/\\/g, "/")}'`).join("\n"));
  const silent = path.join(TAKES, "master-silent.mp4");
  ff(["-f", "concat", "-safe", "0", "-i", joinList, "-c", "copy", silent]);

  if (!args.voice) {
    console.log(`\n✓ ${silent}`);
    console.log(`  runtime ${tc(total)} · voice cues in demo-takes/CUE-SHEET.md`);
    return;
  }

  // Voice (and optional music) mix — the zero-editor path.
  const vdir = path.resolve(String(args.voice));
  const clips = VOICE_CUES.map(([clip, scene, off]) => {
    const base = path.join(vdir, clip);
    const file = [".mp3", ".wav", ".m4a", ".mp4"].map((e) => base + e).find((f) => fs.existsSync(f));
    const at = scene === 12 ? endCardStart + off : starts[scene - 1] + off;
    return { clip, file, at };
  });
  const missing = clips.filter((c) => !c.file);
  if (missing.length) {
    console.error(`✗ missing voice files in ${vdir}: ${missing.map((m) => m.clip).join(", ")}`);
    process.exit(1);
  }

  console.log("→ mixing voice …");
  const inputs = ["-i", silent];
  const filters = [];
  const labels = [];
  clips.forEach((c, i) => {
    inputs.push("-i", c.file);
    filters.push(`[${i + 1}:a]adelay=${Math.round(c.at * 1000)}|${Math.round(c.at * 1000)},apad=whole_dur=${Math.ceil(total)}[v${i}]`);
    labels.push(`[v${i}]`);
  });
  let mixInputs = labels.join("");
  let mixCount = clips.length;
  if (args.music) {
    // The bed LOOPS to cover the full runtime — apad alone padded a short
    // track with silence once it ran out. `-stream_loop -1` makes the input
    // endless; atrim bounds it to the video's length so amix sees a finite
    // stream, and a 3 s fade-out lands exactly on the video's end so the bed
    // closes cleanly instead of being cut mid-note. Volume stays 0.10 (−20 dB).
    inputs.push("-stream_loop", "-1", "-i", path.resolve(String(args.music)));
    const fadeStart = Math.max(0, total - 3);
    filters.push(
      `[${clips.length + 1}:a]atrim=0:${total.toFixed(3)},volume=0.10,` +
      `afade=t=out:st=${fadeStart.toFixed(3)}:d=3[mus]`,
    );
    mixInputs += "[mus]";
    mixCount += 1;
  }
  filters.push(`${mixInputs}amix=inputs=${mixCount}:normalize=0[aout]`);
  const voiced = path.join(TAKES, "master-voiced.mp4");
  ff([...inputs, "-filter_complex", filters.join(";"),
    "-map", "0:v", "-map", "[aout]", "-c:v", "copy", "-c:a", "aac", "-b:a", "192k",
    "-t", String(total), voiced]);
  console.log(`\n✓ ${voiced} — the finished video.`);
}

main().catch((e) => { console.error(e.message ?? e); process.exit(1); });
