# Convert India_MTF_Stock_Lists.xlsx (the owner's MTF refresh-toolkit output)
# into per-broker JSON in scripts/mtf-src/, the common shape build-mtf-margins.mjs
# consumes:  [{ "symbol", "isin", "marginPct", "funded", "category" }]
#
#   python scripts/convert-mtf-workbook.py <path-to-workbook.xlsx>
#
# Rules learned from the workbook itself:
#   - marginPct is the trader's OWN contribution % (sheets verify 100/leverage).
#   - "MTF Funded? = No" rows are APPROVED but not funded — kept with
#     marginPct=100 and funded=false, so the engine prices them as full-cash
#     and the UI can say "approved, not funded" instead of dropping them.
#   - Groww rows harvested from their app sometimes carry a display name in
#     parentheses instead of a ticker; those are resolved by ISIN against the
#     other six sheets, and dropped (counted) when no ISIN exists to resolve.

import json
import re
import sys
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "scripts" / "mtf-src"

SHEETS = {
    "Dhan": "dhan",
    "Zerodha": "zerodha",
    "Upstox": "upstox",
    "Kotak Neo": "kotakneo",
    "Paytm Money": "paytm",
    "Angel One": "angelone",
    "Groww": "groww",
}

SYMBOL_RE = re.compile(r"^[A-Z0-9&.\-]{1,20}$")
ISIN_RE = re.compile(r"^[A-Z]{2}[A-Z0-9]{10}$")


def main(path: str) -> None:
    wb = load_workbook(path, read_only=True, data_only=True)

    # Pull date from the Sources sheet ("Generated by refresh_mtf.py · pulled …").
    as_of = None
    for row in wb["Sources"].iter_rows(values_only=True):
        for c in row:
            if c and "pulled" in str(c):
                m = re.search(r"(\d{4}-\d{2}-\d{2})", str(c))
                if m:
                    as_of = m.group(1)
    print(f"as-of from Sources sheet: {as_of}")

    isin_to_symbol: dict[str, str] = {}
    parsed: dict[str, list[dict]] = {}

    for sheet, key in SHEETS.items():
        ws = wb[sheet]
        rows_out: list[dict] = []
        skipped_symbol = 0
        it = ws.iter_rows(values_only=True)
        header: list[str] | None = None
        for raw in it:
            cells = [str(c) if c is not None else "" for c in raw]
            if header is None:
                if "Symbol" in cells and any("ISIN" in c for c in cells):
                    header = [c.split("\n")[0].strip() for c in cells]
                continue
            row = dict(zip(header, raw))
            symbol = str(row.get("Symbol") or "").strip().upper()
            isin = str(row.get("ISIN") or "").strip().upper()
            margin = row.get("Margin Requirement")
            funded_txt = str(row.get("MTF Funded?") or "")
            category = str(row.get("Category") or "").strip() or None
            if category in ("NONE", "None"):
                category = None

            if not symbol and not isin:
                continue
            try:
                m = float(margin)
            except (TypeError, ValueError):
                continue
            if not (0 < m <= 100):
                continue
            funded = funded_txt.startswith("Yes")
            if not funded:
                m = 100.0  # approved but ₹0 funding — full cash in practice

            rows_out.append(
                {
                    "symbol": symbol,
                    "isin": isin if ISIN_RE.fullmatch(isin) else None,
                    "marginPct": round(m, 1),
                    "funded": funded,
                    "category": category,
                }
            )

        parsed[key] = rows_out
        for r in rows_out:
            if r["isin"] and SYMBOL_RE.fullmatch(r["symbol"] or ""):
                isin_to_symbol.setdefault(r["isin"], r["symbol"])
        print(f"{sheet:12s} parsed {len(rows_out)}")

    # Second pass — repair symbols that aren't tickers (Groww's "(Name)" rows).
    for key, rows_out in parsed.items():
        fixed = dropped = 0
        cleaned = []
        for r in rows_out:
            if not SYMBOL_RE.fullmatch(r["symbol"] or ""):
                resolved = isin_to_symbol.get(r["isin"] or "")
                if resolved:
                    r["symbol"] = resolved
                    fixed += 1
                else:
                    dropped += 1
                    continue
            cleaned.append(r)
        # One row per symbol — funded beats unfunded, then lowest margin.
        best: dict[str, dict] = {}
        for r in cleaned:
            cur = best.get(r["symbol"])
            if cur is None or (r["funded"], -r["marginPct"]) > (cur["funded"], -cur["marginPct"]):
                best[r["symbol"]] = r
        parsed[key] = sorted(best.values(), key=lambda r: r["symbol"])
        if fixed or dropped:
            print(f"  {key}: {fixed} symbols resolved by ISIN, {dropped} dropped (no ISIN to resolve)")
        (OUT / f"{key}.json").write_text(json.dumps({"asOf": as_of, "rows": parsed[key]}, indent=1))

    total = sum(len(v) for v in parsed.values())
    print(f"✓ {total} rows across {len(parsed)} brokers → scripts/mtf-src/*.json")


if __name__ == "__main__":
    main(sys.argv[1])
