"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { AccountDeleteDialog } from "@/components/settings/account-delete-dialog";
export function AccountManager({accounts}:{accounts:{id:number;name:string;broker:string|null;accountRef:string|null;equityCapital:number|null;activeCapital:number|null;archived:boolean;isDefault:boolean}[]}){const router=useRouter();const[busy,setBusy]=useState(false);const[deleteId,setDeleteId]=useState<number|null>(null);const deleteFor=accounts.find(a=>a.id===deleteId)??null;async function save(form:HTMLFormElement){const f=new FormData(form);setBusy(true);await fetch("/api/accounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"upsert",name:f.get("name"),broker:f.get("broker")||null,accountRef:f.get("ref")||null,equityCapital:Number(f.get("equity"))||null,activeCapital:Number(f.get("active"))||null,archived:false})});setBusy(false);form.reset();router.refresh();}return <Card><CardHeader><CardTitle>Portfolio accounts</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 md:grid-cols-3">{accounts.map(a=><div key={a.id} className="rounded-md border border-border p-3 text-xs"><div className="flex items-start justify-between gap-2"><p className="font-medium">{a.name}</p>{accounts.length>1&&<Button type="button" variant="ghost" size="sm" className="h-6 px-2 text-[0.6875rem] text-loss" onClick={()=>setDeleteId(a.id)}>Delete</Button>}</div><p className="text-muted-foreground">{a.broker||"Any broker"}{a.accountRef?` · ${a.accountRef}`:""}</p><p className="mt-1 tabular-nums">Equity {a.equityCapital==null?"inherits global":`₹${a.equityCapital.toLocaleString("en-IN")}`} · F&O {a.activeCapital==null?"inherits global":`₹${a.activeCapital.toLocaleString("en-IN")}`}</p></div>)}</div>{deleteFor&&<AccountDeleteDialog account={deleteFor} accounts={accounts} open={deleteId!==null} onOpenChange={v=>{if(!v)setDeleteId(null);}}/>}<form className="grid gap-3 md:grid-cols-6" onSubmit={e=>{e.preventDefault();void save(e.currentTarget)}}><div><Label>Name</Label><Input name="name" required placeholder="Primary Zerodha"/></div><div><Label>Broker</Label><Input name="broker" placeholder="zerodha"/></div><div><Label>Account ref</Label><Input name="ref" placeholder="masked ID"/></div><div><Label>Equity capital ₹</Label><Input name="equity" type="number" min="0"/></div><div><Label>F&O capital ₹</Label><Input name="active" type="number" min="0"/></div><div className="flex items-end"><Button disabled={busy}>{busy?"Saving…":"Add account"}</Button></div></form><p className="text-[0.6875rem] text-muted-foreground">Account references are labels, not login credentials. “All accounts” consolidates the book; selecting one scopes account-aware reports and new imports.</p></CardContent></Card>}
